env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends: 
  - eslint:recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: "module"
plugins:
rules:
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  eqeqeq: error
  no-trailing-spaces: warn
  object-curly-spacing:
    - error
    - always
  arrow-spacing:
    - error
    - { before: true, after: true }
