env:
  browser: true
  commonjs: true
  es2021: true
  jest: true
  jest/globals: true
  cypress/globals: true
extends: 
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: "module"
plugins:
  - react
  - jest
  - cypress
rules:
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  eqeqeq: error
  no-trailing-spaces: warn
  object-curly-spacing:
    - error
    - always
  arrow-spacing:
    - error
    - { before: true, after: true }
  no-console: 0
  react/prop-types: 0
settings:
  react: { version: detect }
